### ISSUE TITLE
Please add double struck letters

### ISSUE THREAD

**Issue by david-a-wheeler** [fred-wang/Mathzilla#32] opened 2015-12-23 13:48 UTC
Please add double struck letters.  E.g. Unicode hex 2102 (decimal 8450) is double struck capital C. This is often used to represent complex numbers, for example in http://us.metamath.org/mpeuni/2p2e4.html

Similarly 2124 (double struck capital Z) is conventionally used to represent the integers, 2115 is used to represent the natural numbers, 2118 is used to represent the rational numbers and 211d is used to represent the real numbers.

**Comment by fred-wang** [comment] 2015-12-28 13:50
I'm closing that one, since that's probably a duplicate of #31

**Closed by fred-wang** 2015-12-28 13:50 UTC
